### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Bakkerdaan** [thomasp85/lime#69] opened 2018-01-26 08:09 UTC
dear all,

I noticed that if there is a imbalanced variable in the model (in my case, a GLM from the binomial family, and a non-response variable with 300000 TRUE and 11 FALSE) than it will build an explainer, but it will not build an explanation with a contrast error. as soon as I delete the imbalanced variables, it does work.

has anyone encountered this?

regards, Daan

**Comment by thomasp85** [comment] 2018-02-12 19:16
hmm... this seems to be an issue with permutations being of zero variance - these columns should be ignored. Can I get you to retry with the Github version? if there is still problems I will need a reproducible example

**Comment by thomasp85** [comment] 2018-03-05 13:32
Closing - will reopen if a reproducible example is provided

**Closed by thomasp85** 2018-03-05 13:32 UTC
